version: '3'

vars:
  cluster_name: dark5
  cluster_host: microuser-DARK5

  dark5address: "192.168.3.17"
  dark5user: "microuser"

  ssh_command: "ssh {{.dark5user}}@{{.dark5address}}"

  tunnel_remote_host:
    sh: "gostore cat ihc/p641965-amsterdam/common ip"

  k3d_config: k3d.yaml

tasks:
  create:
    cmds:
      # create cluster
      - "{{ .ssh_command }} -- k3d cluster create {{.cluster_name}} --config=- < {{ .k3d_config }}"

  start:
    cmds:
      - "{{ .ssh_command }} -- k3d cluster start {{.cluster_name}}"

  stop:
    cmds:
      - "{{ .ssh_command }} -- k3d cluster stop {{.cluster_name}}"

  delete:
    cmds:
      - "{{ .ssh_command }} -- k3d cluster delete {{.cluster_name}}"

  install-kubeconfig:
    cmds:
      - "{{ .ssh_command }} -- cat /home/{{ .dark5user }}/.kube/config > ~/.kube/dark5.yml"

  delete-kubeconfig:
    cmds:
      - "rm -rf ~/.kube/dark5.yml"

  up-tunnel:
    env:
      REMOTE_HOST: "{{ .tunnel_remote_host }}"
    cmds:
      - "{{ .ssh_command }} -- REMOTE_HOST=$REMOTE_HOST docker compose -f - up -d < docker-compose.yml"

  down-tunnel:
    env:
      REMOTE_HOST: "{{ .tunnel_remote_host }}"
    cmds:
      - "{{ .ssh_command }} -- docker compose -f - down < docker-compose.yml"