apiVersion: v1
kind: PersistentVolume
metadata:
  name: masterdb-host-volume
  labels:
    directory: masterdb
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /data/masterdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masterdb-host-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      directory: masterdb