address := `gostore cat vps1/vm/vm53841/common address`
dockerHost := "ssh://root@" + address
dockerCompose := (invocation_directory() + "/" + "docker-compose.yaml")

up $DOCKER_HOST=dockerHost $COMPOSE_FILE=dockerCompose:
    docker compose up -d

down $DOCKER_HOST=dockerHost $COMPOSE_FILE=dockerCompose:
    docker compose down

manage $DOCKER_HOST=dockerHost $COMPOSE_FILE=dockerCompose:
    zsh