apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-host-volume
  labels:
    directory: filebrowser
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /data/filebrowser
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-host-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      directory: filebrowser