version: "3.7"

services:
    patcherservice:
        image: ${REGISTRY}-patcherservice:master
        container_name: patcherservice
        restart: always
        labels:
            com.curiosityctl.repo: git@github.com:CuriosityPlatform/patcher.git
            com.curiosityctl.log: 1
        ports:
            - "8001:8001"
        depends_on:
            - db
        environment:
            SERVE_REST_ADDRESS: :8001
            SERVE_GRPC_ADDRESS: :8002
            DB_USER: root
            DB_PASSWORD: 1234
            DB_HOST: patcherservice-db
            DB_NAME: patcherservice
            TOKEN_SECRET_KEY: ${PATCHER_SECRET_KEY}
        networks:
            default:
                aliases:
#                      named apigateway to set correct title in nginx.conf
                    -  apigateway

    db:
        image: percona
        container_name: services-db
        restart: always
        labels:
            com.curiosityctl.wait: 1
            com.curiosityctl.boot: 1
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        healthcheck:
            test: mysql -h127.0.0.1 -uroot -p1234 -e 'SELECT 1'
            interval: 20s
            timeout: 1s
        networks:
            default:
                aliases:
                    - patcherservice-db

    nginx:
        image: services-nginx:1.21.1
        build:
            dockerfile: Dockerfile
            context: docker/nginx
        container_name: services-nginx
        restart: always
        depends_on:
            - patcherservice
        ports:
            - "80:80"
            - "443:443"
            - "8002:8002"

volumes:
    db: