apiVersion: v1
kind: PersistentVolume
metadata:
  name: keydrive-host-volume
  labels:
    directory: keydrive
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /data/keydrive
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keydrive-host-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      directory: keydrive