version: "3.7"

services:
  wg:
    container_name: wg
    image: ghcr.io/wg-easy/wg-easy:11
    environment:
      - WG_HOST=${WG_ADDRESS}
      - PASSWORD=${WG_ADMIN_PASS}
    volumes:
      - "~/.wg-easy:/etc/wireguard"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1