version: '3'

vars:
  cluster_name: local

tasks:
  create:
    cmds:
      - k3d cluster create {{.cluster_name}} --config k3d.yaml

  start:
    cmds:
      - k3d cluster start {{.cluster_name}}
  
  stop:
    cmds:
      - k3d cluster stop {{.cluster_name}}

  delete:
    cmds:
      - k3d cluster delete {{.cluster_name}}