mod modules "modules/justfile"

kubeconfigOut := (invocation_directory() + "/" + "modules/.kube.yaml")

[doc("Up dark5 cluster")]
up: _init && _wait-config _install-kubeconfig
  terraform apply

[doc("Remove dark5 cluster")]
down: _init && _remove-kubeconfig
    terraform destroy

[doc("ZSH with configured env")]
manage $KUBECONFIG=kubeconfigOut:
    zsh

_init:
    terraform init

@_wait-config:
    echo "Wait for kubeconfig..."
    sleep 20

@_install-kubeconfig:
    docker cp k3s-server:/output/kubeconfig.yaml {{kubeconfigOut}}

@_remove-kubeconfig:
    rm -rf {{kubeconfigOut}}
