version: '3'

vars:
  project: "k3s"

tasks:
  install:
    cmds:
      - task: up
      - task: kubeconfig

  uninstall:
    cmds:
      - task: down
      - task: kubeconfigrm

  up:
    cmds:
      - task: copy
      - "ssh -F {{.SSH_FILE}} {{.SSH_HOST}} -- 'docker compose --project-directory ~/{{.project}} up -d'"

  copy:
    cmds:
      - "ssh -F {{.SSH_FILE}} {{.SSH_HOST}} -- 'mkdir -p ~/{{.project}}'"
      - "scp -F {{.SSH_FILE}} compose.yaml {{.SSH_HOST}}:~/{{.project}}/compose.yaml"

  kubeconfig:
    cmds:
      - scp -F {{.SSH_FILE}} {{.SSH_HOST}}:~/{{.project}}/kubeconfig.yaml kubeconfig.yaml
      # copy to local configs
      - mv kubeconfig.yaml ~/.kube/config/default.yaml

  kubeconfigrm:
    cmd: ~/.kube/config/default.yaml

  stop:
    cmd: "ssh -F {{.SSH_FILE}} {{.SSH_HOST}} -- 'docker compose --project-directory ~/{{.project}} down -v'"

  down:
    cmds:
      - task: stop
      - "ssh -F {{.SSH_FILE}} {{.SSH_HOST}} rm -rf ~/{{.project}}"

  stats:
    cmd: "ssh -F {{.SSH_FILE}} {{.SSH_HOST}} -- 'docker compose --project-directory ~/{{.project}} stats'"

  ps:
    cmd: "ssh -F {{.SSH_FILE}} {{.SSH_HOST}} -- 'docker compose --project-directory ~/{{.project}} ps'"
