version: '3'

vars:
  project: "k3s"

  ssh_host: "lima-dark5-test"
  ssh_file: "/Users/vadim.makerov/.lima/dark5-test/ssh.config"

tasks:
  up:
    cmds:
      - task: copy
      - "ssh -F {{.ssh_file}} {{.ssh_host}} -- 'docker compose --project-directory ~/{{.project}} up -d'"

  copy:
    cmds:
      - "ssh -F {{.ssh_file}} {{.ssh_host}} -- 'mkdir -p ~/{{.project}}'"
      - "scp -F {{.ssh_file}} compose.yaml lima-dark5-test:~/{{.project}}/compose.yaml"

  kubeconfig:
    cmds:
      - scp -F {{.ssh_file}} lima-dark5-test:~/{{.project}}/kubeconfig.yaml kubeconfig.yaml
      # copy to local configs
      - mv kubeconfig.yaml ~/.kube/config/default.yaml

  stop:
    cmd: "ssh -F {{.ssh_file}} {{.ssh_host}} -- 'docker compose --project-directory ~/{{.project}} down -v'"

  down:
    cmds:
      - task: stop
      - "ssh -F {{.ssh_file}} {{.ssh_host}} rm -rf ~/{{.project}}"
