apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot
  labels:
    app: telegrambot
    tier: service
spec:
  replicas: 1
  strategy:
    # Since currently used pull model to get updates from telegram should use 1 replica and recreate strategy
    type: Recreate
  selector:
    matchLabels:
      app: telegrambot
      tier: service
  template:
    metadata:
      labels:
        app: telegrambot
        tier: service
    spec:
      containers:
        - name: telegrambot
          image: registry.makerov.space:5000/telegrambot:master
          imagePullPolicy: Always
          env:
            - name: TELEGRAM_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: telegramAPIToken
                  name: telegrambot-secret
            - name: NOTION_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  key: notionSecretToken
                  name: telegrambot-secret
            - name: AUTHORIZED_USER_ID
              valueFrom:
                secretKeyRef:
                  key: authorizedUserID
                  name: telegrambot-secret
            - name: NOTION_DATABASE_ID
              value: d74fd98c396144e4b8d62d66fe47ae8a
            - name: NOTION_RESOURCE_DATABASE_ID
              value: f984f98ac57c4f26810015b969f621c5