apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: curiosity

volumes:
  # Mount data folder
  - volume: {{PROJECT_ROOT_DIR}}/env/k3d/data:/data

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer