apiVersion: v1
kind: PersistentVolume
metadata:
  name: restic-pv
  labels:
    directory: restic-data
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /mnt/bag/restic
  # Place pv at agent-1 node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: In
              values:
                - "true"
