apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-data-volume
  labels:
    directory: transmission-data
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /mnt/bag/transmission
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-data-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      directory: transmission-data