apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-data-2-volume
  labels:
    directory: filebrowser-data-2
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /mnt/bag
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data-2-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      directory: filebrowser-data-2