apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-database-volume
  labels:
    directory: filebrowser-database
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /mnt/data/filebrowser-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-database-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      directory: filebrowser-database