apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdns
  labels:
    app: duckdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duckdns
  template:
    metadata:
      labels:
        app: duckdns
    spec:
      containers:
        - name: duckdns
          image: lscr.io/linuxserver/duckdns:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SUBDOMAINS
              value: storage-makerovspace
            - name: TOKEN
              value: "token"
