apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: curiosity

kubeAPI:
  host: "makerov.space"

volumes:
  # Mount data folder
  - volume: /usr/local/curiosity/data:/data

registries:
  create:
    name: registry.makerov.space
    hostPort: "5000"
    volumes:
      - /usr/local/curiosity/registry:/var/lib/registry