apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - filebrowser.yaml

configMapGenerator:
  - name: ingress-access-config
    files:
      - ingress-access-conf

# Inject cookie access to nginx ingreses which has non-empty field nginx.ingress.kubernetes.io/configuration-snippet
replacements:
  - source:
      fieldPath: data.ingress-access-conf
      kind: ConfigMap
      name: ingress-access-config
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - metadata.annotations.[nginx.ingress.kubernetes.io/configuration-snippet]