apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: registry-ui
    tier: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
      tier: registry
  template:
    metadata:
      labels:
        app: registry-ui
        tier: registry
    spec:
      containers:
        - name: registry-ui
          image: snagles/docker-registry-manager
          imagePullPolicy: IfNotPresent
          env:
            - name: MANAGER_PORT
              value: "8080"
            - name: MANAGER_REGISTRIES
              value: "/config/registries.yml"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: registry-config
              mountPath: /config
      volumes:
        - name: registry-config
          configMap:
            name: registry-config
            items:
              - key: registries.yml
                path: registries.yml

---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
spec:
  type: ClusterIP
  selector:
    app: registry-ui
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080