apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      initContainers:
        # preallocate necessary folders for transmission
        - name: busybox
          image: busybox
          command:
            - sh
            - "-c"
            - mkdir -p /downloads/complete && mkdir -p /downloads/incomplete
          volumeMounts:
            - name: transmission-data-volume
              mountPath: /downloads

      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:4.0.5
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          ports:
            - containerPort: 9091
              name: http
          volumeMounts:
            - name: transmission-data-volume
              mountPath: /downloads

      volumes:
        - name: transmission-data-volume
          persistentVolumeClaim:
            claimName: transmission-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  selector:
    app: transmission
  ports:
    - port: 9091
      protocol: TCP
      targetPort: 9091
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-pvc
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      directory: transmission-data