version: '3'

vars:
  name: dark5-test
  template: docker-rootful

tasks:
  boot:
    cmds:
      - "limactl start --name={{.name}} template://{{.template}}"
      - "cp ~/.lima/{{.name}}/ssh.config ssh.config"

  stop:
    cmd: "limactl stop {{.name}}"

  teardown:
    cmds:
      - task: stop
      - "limactl delete {{.name}}"
      - "rm ssh.config"